### ISSUE TITLE
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked 

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-registry#34]
while trying to make the beast busy while triggering updates for all (>5k) urls got following traceback

<details>
<summary>full traceback</summary> 

```shell
127.0.0.1 - - [16/Jul/2021 10:21:07] "GET /v1/datasets/d20dd376-28b2-11ea-b0ce-0025904abcb0/urls/aHR0cHM6Ly9kYXRhc2V0cy5kYXRhbGFkLm9yZy9oY3Atb3BlbmFjY2Vzcy9IQ1AxMjAwLzE2NjQzOC9UMXcvLmdpdA== HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1236, in _execute_context
    cursor, statement, parameters, context
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 536, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad-registry/venvs/dev3/lib/python3.7/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/yoh/proj/datalad/datalad-registry/venvs/dev3/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/home/yoh/proj/datalad/datalad-registry/venvs/dev3/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/yoh/proj/datalad/datalad-registry/venvs/dev3/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/yoh/proj/datalad/datalad-registry/venvs/dev3/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/yoh/proj/datalad/datalad-registry/venvs/dev3/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/yoh/proj/datalad/datalad-registry/datalad_registry/dataset_urls.py", line 45, in url
    row_known = result.first()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2979, in first
    ret = list(self[0:1])
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2771, in __getitem__
    return list(res)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 3081, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 3106, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 980, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/elements.py", line 273, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1099, in _execute_clauseelement
    distilled_params,
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1240, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1458, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 276, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1236, in _execute_context
    cursor, statement, parameters, context
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 536, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: 'SELECT urls.url AS urls_url, urls.ds_id AS urls_ds_id, urls.annex_uuid AS urls_annex_uuid, urls.annex_key_count AS urls_annex_key_count, urls.info_ts AS urls_info_ts, urls.update_announced AS urls_update_announced, urls.head AS urls_head, urls.head_describe AS urls_head_describe, urls.branches AS urls_branches, urls.tags AS urls_tags \nFROM urls \nWHERE urls.url = ? AND urls.ds_id = ?\n LIMIT ? OFFSET ?'] [parameters: ('https://datasets.datalad.org/hcp-openaccess/HCP1200/166438/T1w/.git', 'd20dd376-28b2-11ea-b0ce-0025904abcb0', 1, 0)] (Background on this error at: http://sqlalche.me/e/e3q8)

```
</details>

<details>
<summary>submission loop also reported a good number of errors</summary> 

```shell
registry-submit(ok): /mnt/btrfs/datasets/datalad/crawl/hcp-openaccess/HCP1200/172635/unprocessed (dataset) [Announced update: https://datasets.datalad.org/hcp-openaccess/HCP1200/172635/unprocessed/.git]
[ERROR] Submitting URL failed: HTTPConnectionPool(host='127.0.0.1', port=5000): Read timed out. (read timeout=1) [registry-submit(/mnt/btrfs/datasets/datalad/crawl/hcp-openaccess/HCP1200/172938)]
registry-submit(error): /mnt/btrfs/datasets/datalad/crawl/hcp-openaccess/HCP1200/172938 (dataset) [Submitting URL failed: HTTPConnectionPool(host='127.0.0.1', port=5000): Read timed out. (read timeout=1)]
[ERROR] Submitting URL failed: HTTPConnectionPool(host='127.0.0.1', port=5000): Read timed out. (read timeout=1) [registry-submit(/mnt/btrfs/datasets/datalad/crawl/hcp-openaccess/HCP1200/172938/MNINonLinear)]
registry-submit(error): /mnt/btrfs/datasets/datalad/crawl/hcp-openaccess/HCP1200/172938/MNINonLinear (dataset) [Submitting URL failed: HTTPConnectionPool(host='127.0.0.1', port=5000): Read timed out. (read timeout=1)]
registry-submit(ok): /mnt/btrfs/datasets/datalad/crawl/hcp-openaccess/HCP1200/172938/T1w (dataset) [Announced update: https://datasets.datalad.org/hcp-openaccess/HCP1200/172938/T1w/.git]
[ERROR] Submitting URL failed: HTTPConnectionPool(host='127.0.0.1', port=5000): Read timed out. (read timeout=1) [registry-submit(/mnt/btrfs/datasets/datalad/crawl/hcp-openaccess/HCP1200/172938/unprocessed)]
registry-submit(error): /mnt/btrfs/datasets/datalad/crawl/hcp-openaccess/HCP1200/172938/unprocessed (dataset) [Submitting URL failed: HTTPConnectionPool(host='127.0.0.1', port=5000): Read timed out. (read timeout=1)]
registry-submit(ok): /mnt/btrfs/datasets/datalad/crawl/hcp-openaccess/HCP1200/173132 (dataset) [Announced update: https://datasets.datalad.org/hcp-openaccess/HCP1200/173132/.git]
registry-submit(ok): /mnt/btrfs/datasets/datalad/crawl/hcp-openaccess/HCP1200/173132/MNINonLinear (dataset) [Announced update: https://datasets.datalad.org/hcp-openaccess/HCP1200/173132/MNINonLinear/.git]
[ERROR] Submitting URL failed: HTTPConnectionPool(host='127.0.0.1', port=5000): Read timed out. (read timeout=1) [registry-submit(/mnt/btrfs/datasets/datalad/crawl/hcp-openaccess/HCP1200/173132/T1w)]
registry-submit(error): /mnt/btrfs/datasets/datalad/crawl/hcp-openaccess/HCP1200/173132/T1w (dataset) [Submitting URL failed: HTTPConnectionPool(host='127.0.0.1', port=5000): Read timed out. (read timeout=1)]
[ERROR] Submitting URL failed: HTTPConnectionPool(host='127.0.0.1', port=5000): Read timed out. (read timeout=1) [registry-submit(/mnt/btrfs/datasets/datalad/crawl/hcp-openaccess/HCP1200/173132/unprocessed)]
registry-submit(error): /mnt/btrfs/datasets/datalad/crawl/hcp-openaccess/HCP1200/173132/unprocessed (dataset) [Submitting URL failed: HTTPConnectionPool(host='127.0.0.1', port=5000): Read timed out. (read timeout=1)]
[ERROR] Submitting URL failed: HTTPConnectionPool(host='127.0.0.1', port=5000): Read timed out. (read timeout=1) [registry-submit(/mnt/btrfs/datasets/datalad/crawl/hcp-openaccess/HCP1200/173233)]
registry-submit(error): /mnt/btrfs/datasets/datalad/crawl/hcp-openaccess/HCP1200/173233 (dataset) [Submitting URL failed: HTTPConnectionPool(host='127.0.0.1', port=5000): Read timed out. (read timeout=1)]
^C^Cregistry-submit(ok): /mnt/btrfs/datasets/datalad/crawl/hcp-openaccess/HCP1200/173233/MNINonLinear (dataset) [Announced update: https://datasets.datalad.org/hcp-openaccess/HCP1200/173233/MNINonLinear/.git]
[ERROR] [Errno 32] Broken pipe [ansitowin32.py:write_plain_text:175] (BrokenPipeError)

```
</details>

and webui showed the trace... looking at console -- it was full of such errors.  Might be due to the "collision" between cron job updating first 3 (ATM) datasets and the PATCH job -- I have not spotted any protection for parallel operations ATM.  I guess the easiest resolution ATM could be just defer any updates to the cron job.

edit: sqlite doesn't really support concurrency well: https://docs.sqlalchemy.org/en/14/dialects/sqlite.html#database-locking-behavior-concurrency ; and anyways to scale we should switch to some more "full fledged" DB, so probably adding postgres container into docker compose setup to go along with celery would provide remedy

**Comment by yarikoptic** [comment]
@candleindark do you think it might remain the issue to attend to or we somehow escaped it by now since you had thousands processed just fine. Do you have logs for that run -- is there any `sqlite3.OperationalError: database is locked` messages reported?

**Comment by candleindark** [comment]
From the beginning of my work in this project, Postgres has been the database. I believe `sqlite3.OperationalError: database is locked` is an error particular to SQLite, and I have never encountered this error in this project.

I just checked the logs of the podman containers running datalad-registry and found no error of such kind.

**Comment by yarikoptic** [comment]
rright! we did that in https://github.com/datalad/datalad-registry/pull/39 !
